name: billiards
description: "Professional billiards game with player statistics and ratings"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get: ^4.7.2
  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  objectbox_generator: ^4.2.0
  riverpod: ^2.6.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.5.0
  fl_chart: ^0.71.0
  flutter_gen_runner: ^5.4.0
  audioplayers: ^5.2.1
  event_bus: ^2.0.0
  flutter_local_notifications: ^19.2.1 
  intl: ^0.20.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#2C3E50"
  color_dark: "#1E1E1E"
  image: assets/icon/icon.png
  android_12:
    image: assets/icon/icon.png
    icon_background_color: "#2C3E50"
    icon_background_color_dark: "#1E1E1E"
  web: false
  android: true
  ios: true
  fullscreen: true


